// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remote_fused_graph_execute_info.proto

package org.tensorflow.framework;

public final class RemoteFusedGraphExecuteInfoProto {
  private RemoteFusedGraphExecuteInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RemoteFusedGraphExecuteInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RemoteFusedGraphExecuteInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RemoteFusedGraphExecuteInfo_TensorShapeTypeProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RemoteFusedGraphExecuteInfo_TensorShapeTypeProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%remote_fused_graph_execute_info.proto\022" +
      "\ntensorflow\032\016node_def.proto\032\022tensor_shap" +
      "e.proto\032\013types.proto\"\371\003\n\033RemoteFusedGrap" +
      "hExecuteInfo\022!\n\004node\030\001 \003(\0132\023.tensorflow." +
      "NodeDef\022\035\n\025graph_input_node_name\030\002 \003(\t\022\036" +
      "\n\026graph_output_node_name\030\003 \003(\t\022\025\n\rexecut" +
      "or_name\030\004 \001(\t\022&\n\036serialized_executor_par" +
      "ameters\030\005 \001(\014\022f\n default_graph_input_ten" +
      "sor_shape\030\006 \003(\0132<.tensorflow.RemoteFused" +
      "GraphExecuteInfo.TensorShapeTypeProto\022g\n",
      "!default_graph_output_tensor_shape\030\007 \003(\013" +
      "2<.tensorflow.RemoteFusedGraphExecuteInf" +
      "o.TensorShapeTypeProto\032h\n\024TensorShapeTyp" +
      "eProto\022#\n\005dtype\030\001 \001(\0162\024.tensorflow.DataT" +
      "ype\022+\n\005shape\030\002 \001(\0132\034.tensorflow.TensorSh" +
      "apeProtoBA\n\030org.tensorflow.frameworkB Re" +
      "moteFusedGraphExecuteInfoProtoP\001\370\001\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.NodeProto.getDescriptor(),
          org.tensorflow.framework.TensorShapeProtos.getDescriptor(),
          org.tensorflow.framework.TypesProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_RemoteFusedGraphExecuteInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_RemoteFusedGraphExecuteInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RemoteFusedGraphExecuteInfo_descriptor,
        new java.lang.String[] { "Node", "GraphInputNodeName", "GraphOutputNodeName", "ExecutorName", "SerializedExecutorParameters", "DefaultGraphInputTensorShape", "DefaultGraphOutputTensorShape", });
    internal_static_tensorflow_RemoteFusedGraphExecuteInfo_TensorShapeTypeProto_descriptor =
      internal_static_tensorflow_RemoteFusedGraphExecuteInfo_descriptor.getNestedTypes().get(0);
    internal_static_tensorflow_RemoteFusedGraphExecuteInfo_TensorShapeTypeProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RemoteFusedGraphExecuteInfo_TensorShapeTypeProto_descriptor,
        new java.lang.String[] { "Dtype", "Shape", });
    org.tensorflow.framework.NodeProto.getDescriptor();
    org.tensorflow.framework.TensorShapeProtos.getDescriptor();
    org.tensorflow.framework.TypesProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
